### ISSUE TITLE
mapa mental 

### ISSUE THREAD

**Issue by elisa1223** [SistemasTecTlaxiaco/actividad-4-mapa-mental-elisa1223#2]
[mapa_mental.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-elisa1223/files/12680711/mapa_mental.pdf)

**Comment by 00Asaf00** [comment]
- Manejo: 25%
- Relaciones: 25%
- Calidad: 20%
- Jerarquía: 25%

Calificación:
(95%)/100*20 = 19/20

Comentarios:

- Toda la información es válida, coherente y fácil de interpretar, sin embargo, falta un poco más de creatividad en el diseño del mapa.

Evaluado por el Equipo de Edgar Iván

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
